#项目全局配置
server:
  context-path: /dealer
  port: 8888

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bodyguard?characterEncoding=UTF-8
    name: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 139.196.229.158
      port: 27017
      database: gprs
      username: root
      password: HZjiawawulian@163

